name: build and publish release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs: 
    build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Package
        run: |
          pyinstaller -F main.py
      - name: Upload artifact for release job
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe
          retention-days: 1

    release-please:
      runs-on: ubuntu-latest
      needs: build
      steps:      
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: python
          default-branch: main
          token: ${{ secrets.RELEASE_TOKEN }}
      
